# Generated by Django 3.2.12 on 2022-05-06 22:37

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='categories/default.png', null=True, upload_to=course.models.get_category),
        ),
    ]
