# Generated by Django 3.2.12 on 2022-05-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_home',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lesson',
        ),
    ]
